chore: ci/cd adding coding style checker

diff --git a/.github/workflows/ftp.yml b/.github/workflows/ftp.yml
--- a/.github/workflows/ftp.yml
+++ b/.github/workflows/ftp.yml
@@ -16,8 +16,32 @@ on:
       - '.github/workflows/**'
 
 jobs:
+  check_coding_style:
+    runs-on: ubuntu-latest
+    container:
+      image:  ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: check_coding_style
+        run: |
+          check.sh "$(pwd)" "$(pwd)"
+          codingLogFile="$(pwd)/coding-style-reports.log"
+          if [ -s "$codingLogFile" ]; then
+            while IFS= read -r line; do
+              IFS=':' read -ra fields <<< "$line"
+              file="${fields[0]}"
+              line="${fields[1]}"
+              name="${fields[2]}"
+              type="${fields[3]}"
+              echo "::error title=$name coding style error,file=$file,line=$line::$type"
+            done < "$codingLogFile"
+            exit 1
+          else
+            echo "No coding style errors detected"
+          fi
   check_program_compilation:
     runs-on: ubuntu-latest
+    needs: check_coding_style
     container:
       image: epitechcontent/epitest-docker:latest
     steps:
